<?php

return [
    "ATAP" => [
        ["id" => 1, "name" => "PELAT BETON"],
        ["id" => 2, "name" => "GENTENG KERAMIK"],
        ["id" => 3, "name" => "GENTENG PRESS BETON"],
        ["id" => 4, "name" => "ASBES GELOMBANG"],
        ["id" => 5, "name" => "SENG GELOMBANG"],
        ["id" => 6, "name" => "GENTENG SIRAP"],
        ["id" => 7, "name" => "GENTENG TANAH LIAT"],
        ["id" => 8, "name" => "SPANDEK"]
    ],
    "btk_tanah" => [
        ["id" => 1, "name" => "SEGI EMPAT"],
        ["id" => 2, "name" => "SEGI BANYAK"],
        ["id" => 3, "name" => "TDK BERATURAN"],
    ],
    "DINDING" => [
        ["id" => 1, "name" => "KACA/AKUMINIUM"],
        ["id" => 2, "name" => "BETON"],
        ["id" => 3, "name" => "BATU BATA/CONBLOK"],
        ["id" => 4, "name" => "KAYU"],
        ["id" => 5, "name" => "SENG"],
        ["id" => 6, "name" => "TIDAK ADA"],
    ],
    "KONDISI" => [
        ["id" => 1, "name" => "SANGAT BAIK"],
        ["id" => 2, "name" => "BAIK"],
        ["id" => 3, "name" => "SEDANG"],
        ["id" => 4, "name" => "JELEK "],
    ],
    "STRUKTUR" => [
        ["id" => 2, "name" => "BETON"],
        ["id" => 1, "name" => "BAJA"],
        ["id" => 3, "name" => "BATU BATA"],
        ["id" => 4, "name" => "KAYU"],
    ],
    "PAGAR" => [
        ["id" => 1, "name" =>    "BATAKO"],
        ["id" => 2, "name" =>    "BATA"],
        ["id" => 3, "name" =>    "BETON PRACETAK"],
        ["id" => 4, "name" =>    "BESI"],
        ["id" => 5, "name" =>    "BRC"],
    ],
    "TRANSAKSI" => [
        ["id" => 1, "name" => "PEREKAMAN DATA"],
        ["id" => 2, "name" => "PEMUTAKHIRAN DATA"],
        ["id" => 3, "name" => "PENGHAPUSAN DATA"],
        ["id" => 4, "name" => "PENILAIAN INDIVIDU"],
    ],
    "MDD" => [
        ["id" => 'mdd_gyp_imp', "name" => "GYPSUM IMPORT"],
        ["id" => 'mdd_gyp_lkl', "name" => "GYPSUM LOKAL"],
        ["id" => 'mdd_plywood', "name" => "PLYWOOD"],
        ["id" => 'mdd_triplex', "name" => "TRIPLEX"],
        ["id" => 'mdd_batu', "name" => "PASANGAN DINDING 1/2 BATU (1:3)"]
    ],
    "MDL" => [
        ["id" => 'mdl_batu', "name" => "PASANGAN DINDING 1/2 BATU (1:3)"],
        ["id" => 'mdl_kaca', "name" => "KACA"],
        ["id" => 'mdl_celcon', "name" => "Pas. CELCON"],
        ["id" => 'mdl_beton', "name" => "BETON PRA CETAK"],
        ["id" => 'mdl_seng', "name" => "SENG"],
        ["id" => 'mdl_kayu', "name" => "KAYU"],
    ],
    "PDD" => [
        ["id" => "pdd_kaca_imp", "name" => "KACA IMPORT"],
        ["id" => "pdd_kaca_lkl", "name" => "KACA LOKAL"],
        ["id" => "pdd_wallpap", "name" => "WALLPAPER"],
        ["id" => "pdd_cat", "name" => "CAT"],
        ["id" => "pdd_granit_imp", "name" => "GRANIT IMPORT"],
        ["id" => "pdd_granit_lkl", "name" => "GRANIT LOKAL"],
        ["id" => "pdd_marmer_imp", "name" => "MARMER IMPORT"],
        ["id" => "pdd_marmer_lkl", "name" => "MARMER LOKAL"],
        ["id" => "pdd_keramik", "name" => "KERAMIK STANDARD"],
    ],
    "PDL" => [
        ["id" => "pdl_kaca_imp", "name" => "KACA IMPORT"],
        ["id" => "pdl_kaca_lkl", "name" => "KACA LOKAL"],
        ["id" => "pdl_cat", "name" => "CAT"],
        ["id" => "pdl_granit_imp", "name" => "GRANIT IMPORT"],
        ["id" => "pdl_granit_lkl", "name" => "GRANIT LOKAL"],
        ["id" => "pdl_marmer_imp", "name" => "MARMER IMPORT"],
        ["id" => "pdl_marmer_lkl", "name" => "MARMER LOKAL"],
        ["id" => "pdl_keramik", "name" => "KERAMIK STANDARD"],
    ],
    "LANATAI" => [
        ["id" => "pl_granit_imp", "name" => "GRANIT IMPORT"],
        ["id" => "pl_granit_lkl", "name" => "GRANIT LOKAL"],
        ["id" => "pl_marmer_imp", "name" => "MARMER IMPORT"],
        ["id" => "pl_marmer_lkl", "name" => "MARMER LOKAL"],
        ["id" => "pl_keramik", "name" => "KERAMIK LOKAL"],
        ["id" => "pl_vynil", "name" => "VYNIL"],
        ["id" => "pl_karpet_imp", "name" => "KARPET IMPORT"],
        ["id" => "pl_karpet_lkl", "name" => "KARPET LOKAL"],
        ["id" => "pl_kayu", "name" => "KAYU"],
        ["id" => "pl_ubinpc", "name" => "UBIN ABU-ABU"],
        ["id" => "pl_semen", "name" => "SEMEN"],
    ],
    "LANGIT" => [
        ["id" => "lgt_gypsum", "name" => "GYPSUM"],
        ["id" => "lgt_akustik", "name" => "AKUSTIK"],
        ["id" => "lgt_asbes", "name" => "ETERNIT"],
        ["id" => "lgt_triplek", "name" => "TRIPLEK + CAT"],
    ],
];
